# Generated by Django 2.2 on 2019-04-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_auto_20190419_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_app.ProductItem')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
